name: trosko
description: 'Budget tracking application in Flutter.'
publish_to: 'none'
version: 1.5.0+150

#
# DEPLOYING APP
# 1. `pubspec.yaml` -> Bump version number
# 2. `release_notes.txt` -> Update changelog for all languages
# 3. `default.txt` -> Update changelog for all languages
#

#
# Android
# `cd android/ && fastlane play_store_release`
#
# GitHub Releases
# `cd android/ && fastlane github_release`
#
# iOS
# `cd ios/ && fastlane app_store_release`
#

environment:
  sdk: 3.10.4

dependencies:
  flutter:
    sdk: flutter

  animations: 2.1.1
  calendar_date_picker2: 2.0.1
  cloud_firestore: 6.1.1
  diacritic: 0.1.6
  easy_localization: 3.0.8
  firebase_auth: 6.1.3
  firebase_core: 4.3.0
  flutter_animate: 4.5.2
  flutter_colorpicker: 1.1.0
  flutter_displaymode: 0.7.0
  flutter_foreground_task: 9.1.0
  flutter_map: 8.2.2
  flutter_local_notifications: 19.5.0
  flutter_swipe_action_cell: 3.1.6
  fuzzywuzzy: 1.2.0
  geocoding: 4.0.0
  get_it: 9.2.0
  hive_ce: 2.16.0
  hive_ce_flutter: 2.3.3
  intl: 0.20.2
  just_audio: 0.10.5
  latlong2: 0.9.1
  logger: 2.6.2
  notification_listener_service: 0.3.4
  package_info_plus: 9.0.0
  phosphor_flutter: 2.1.0
  scroll_datetime_picker: 0.2.2
  string_similarity: 2.1.1
  uuid: 4.5.2
  watch_it: 2.4.1
  workmanager: 0.9.0+3

dev_dependencies:
  build_runner: 2.10.4
  flutter_launcher_icons: 0.14.4
  flutter_native_splash: 2.4.7
  hive_ce_generator: 1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/ProductSans/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/ProductSans/ProductSans-Light.ttf
          weight: 300
        - asset: assets/ProductSans/ProductSans-Regular.ttf
          weight: 500
        - asset: assets/ProductSans/ProductSans-Medium.ttf
          weight: 600
        - asset: assets/ProductSans/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/ProductSans/ProductSans-Black.ttf
          weight: 900


# Run code generation - `dart run build_runner build -d`

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_launcher_icons:
  image_path_android: 'assets/icon.png'
  image_path_ios: 'assets/icon.png'
  android: true
  ios: true
  adaptive_icon_background: 'assets/background.png'
  adaptive_icon_foreground: 'assets/splash_icon.png'
  adaptive_icon_foreground_inset: 16
  adaptive_icon_monochrome: 'assets/monochrome.png'
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: '#EDEDF4'
  web:
    generate: true
    image_path: 'assets/icon.png'
    background_color: '#EDEDF4'
    theme_color: '#EDEDF4'
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  background_image: 'assets/splash.png'
  background_image_dark: 'assets/splash_dark.png'
  android_12:
    image: 'assets/splash_icon.png'
    image_dark: 'assets/monochrome.png'
    color: '#EDEDF4'
    color_dark: '#1D2024'
